# Basic settings
classic: false

# Blocks
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

# Color
color:
  # when: auto
  theme: custom

# Icons
icons:
  when: auto
  theme: fancy

# Layout
layout: grid

# Sorting
sorting:
  dir-grouping: first

# Date format
date: "+%Y-%m-%d %H:%M"

# Permission format
permission: rwx

# Size format
size: default

# Indicators
indicators: false

# Header
header: false

# Symlink arrow
symlink-arrow: â‡’

